baseURL = 'https://subsid.github.io/'
languageCode = 'en-us'
title = "Siddharth's Blog"
theme = 'PaperMod'
googleAnalytics = 'G-4H9QYNJZV1'

[[menu.main]]
name = "About"
url = "about/"
weight = 1

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 2

[[menu.main]]
name = "Archives"
url = "archives/"
weight = 3

[[menu.main]]
name = "Search"
url = "search/"
weight = 4

[[menu.main]]
name = "RSS"
url = "https://subsid.github.io/index.xml"
weight = 5

[[params.socialIcons]]
name = "twitter"
title = "Twitter"
url = "https://twitter.com/subsid"

# [[socialIcons]]

[params]
  # color style
  color = 'grey'                           # linen, wheat, gray, light

  # header social icons
  twitter = '_subsid'
  linkedin = "subsid"
  rss = true

  # home page profile
  avatar = 'sidharth3930@gmail.com'                 # gravatar email or image url
  name = 'Siddharth'
  bio = ''
  ShowCodeCopyButtons = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

