baseURL = 'https://subsid.github.io/'
languageCode = 'en-us'
title = "Siddharth's Blog"
theme = 'PaperMod'

[params]
  # color style
  color = 'grey'                           # linen, wheat, gray, light

  # header social icons
  twitter = '_subsid'
  rss = true 
  # home page profile
##  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Siddharth'
  bio = ''
