baseURL = 'https://subsid.github.io/'
languageCode = 'en-us'
title = "Siddharth's Blog"
theme = 'PaperMod'
googleAnalytics = 'G-4H9QYNJZV1'

[[menu.main]]
name = "About"
url = "about/"
weight = 5

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[menu.main]]
name = "RSS"
url = "https://subsid.github.io/index.xml"
weight = 12

[params]
  # color style
  color = 'grey'                           # linen, wheat, gray, light

  # header social icons
  twitter = '_subsid'
  rss = true
  # home page profile
  avatar = 'sidharth3930@gmail.com'                 # gravatar email or image url
  name = 'Siddharth'
  bio = ''

