---
title: Physics of Flocking
date: 2017-09-22T04:56:54-05:00
tags: [post, javascript, threejs, graphics]
draft: false
---

As a part my of [[http://courses.cs.tamu.edu/keyser/viza659/Syllabus.html][physics based modelling]] course, I implemented a [[https://subsid.github.io/flocking/dist/][flocking simulation]] using [[https://threejs.org/][threejs]].

Flocking (or Swarming) is a nice example of something known as *emergent behavior* ([[https://en.wikipedia.org/wiki/Emergence][wiki]]).

#+begin_quote
 Emergence is a phenomenon whereby larger entities arise through interactions among smaller or simpler entities such that the larger entities exhibit properties the smaller/simpler entities do not exhibit.
#+end_quote

This behavior is common among various animal groups such as birds, ants, bees, fishes. Here is a nice video of starlings flocking around.

#+BEGIN_export html
<div class="iframe_container">
<iframe width="560" height="315" src="https://www.youtube.com/embed/V4f_1_r80RY?rel=0" frameborder="0" allowfullscreen='allowfullscreen'> </iframe>
</div>
#+END_export

The idea was popularized in the field of graphics by [[https://en.wikipedia.org/wiki/Craig_Reynolds_(computer_graphics)][Craig Reynolds]], when he created the famous [[https://en.wikipedia.org/wiki/Boids][Boids]] artificial life simulation in 1986.

At its core, each Boid (Bird-oid object!) follows three simple rules:

- **Seperation** Avoid crowding local buddies.
- **Alignment** Direction of velocity should be along the average direction of local buddies.
- **Cohesion** Stay centered between local buddies.

And that's it! This leads to some cool emergent behavior. This can be extended in many ways, by adding some obstacle avoidance, common goal and other effects. Something I find really cool is that we can start each boid at some random initial velocity, and see them slowly come together into a nice flock.

The source code is available [[https://github.com/subsid/flocking][here]], in case someone wants to play with it. The implementation is based on [[https://codepen.io/coaster/pen/QpqVjP][this one by Ellie]].

* Blog:Physics of flocking
:PROPERTIES:
:ID: physics-of-flocking
:CUSTOM_ID: hideroamtags
:END:

[[id:145967c8-ebfc-41c6-97ed-d9b7b8a6b415][Blog]] [[id:55f23bfb-af86-47f1-ba37-e0671d409350][Programming Languages]] [[id:1137eac6-6e72-4d1b-9b78-57c4f5185040][Java Script]]

