---
title: "Why are bugs attracted to light"
date: "2018-02-20T02:33:19-05:00"
draft: true
tags: [science, fun facts]
katex: true
markup: mmark
---

#+begin_comment
# [[id:c524a72a-29f3-42ab-9598-88132af425a9][Science]] [[id:86e71295-fe3a-498d-b755-2805397e01a7][Fun Facts]]
#+end_comment

[[https://www.youtube.com/watch?v=oRqOohdLrJE][Smartereveryday video]]

*Entomology* is study of insects.
*Phototaxis* - movement of organism towards or away from light. +ve and -vely phototaxic based on towards or away from light.

** Theory 1
- Moths and other bugs use heavenly bodies like the sun/moon to orient themselves while flying.  They try to align themselves at a certain angle with the moon.  But if the moon is brought superclose, the moth has to pitch up in order to maintain the angle, and this causes a logarithmic spiral into the source.
- People have tried to verify this, and its kinda true, but not always. hmmm

** Theory 2
- This theory says that some species of moths align themselves straight towards a light source
  and fly towards it. (A light source is usually like an opening, making the insect fly towards
  it so that it can fly freely without any objects in between)
